---
xpassthrough:
  filter_field_name: x
  filter_limit_min: -0.25
  filter_limit_max: 0.15
  filter_limit_negative: False
  input_frame: '/world'

ypassthrough:
  filter_field_name: y
  filter_limit_min: 0.1
  filter_limit_max: 0.45
  filter_limit_negative: False
  input_frame: '/world'

zpassthrough:
  filter_field_name: z
  filter_limit_min: 0.075
  filter_limit_max: 0.3
  filter_limit_negative: False
  input_frame: '/world'

input_pc_topic: "/kinect2/hd/points"
output_pc_topic: "/filtered_pc_kinectone"
observed_frame_id: "/kinect2_ir_optical_frame"
filtered_frame_id: "/world"