---
xpassthrough:
  filter_field_name: x
  filter_limit_min: -0.75
  filter_limit_max: 0.15
  filter_limit_negative: False
  input_frame: 'world'

ypassthrough:
  filter_field_name: y
  filter_limit_min: -1.5
  filter_limit_max: -0.1
  filter_limit_negative: False
  input_frame: 'world'

zpassthrough:
  filter_field_name: z
  filter_limit_min: 0.01
  filter_limit_max: 1.0
  filter_limit_negative: False
  input_frame: 'world'


cropbox:
  min_x: -0.5
  min_y: -0.6858
  min_z: 0.02
  max_x: 0.3
  max_y: -0.1524
  max_z: 0.7
  keep_organized: 1
  input_frame: 'world'
