---
xpassthrough:
  filter_field_name: x
  filter_limit_min: -0.3
  filter_limit_max: 0.5
  filter_limit_negative: False
  input_frame: 'world'
  output_frame: 'world'

ypassthrough:
  filter_field_name: y
  filter_limit_min: -1.0
  filter_limit_max: 0.5
  filter_limit_negative: False
  input_frame: 'world'
  output_frame: 'world'

zpassthrough:
  filter_field_name: z
  filter_limit_min: 0.1
  filter_limit_max: 1.0
  filter_limit_negative: False
  input_frame: 'world'
  output_frame: 'world'
  
    
