---
xpassthrough:
  filter_field_name: x
  filter_limit_min: -1.0
  filter_limit_max: .15
  filter_limit_negative: False
  input_frame: 'world' 

ypassthrough:
  filter_field_name: y
  filter_limit_min: -.15
  filter_limit_max: 1.0
  filter_limit_negative: False
  input_frame: 'world'

zpassthrough:
  filter_field_name: z
  filter_limit_min: 0.01
  filter_limit_max: 0.5
  filter_limit_negative: False
  input_frame: 'world'
  
cropbox:
  min_x: -1.0
  min_y: -.15
  min_z: 0.01
  max_x: 0.15
  max_y: 1.0
  max_z: 0.5
  keep_organized: 1
  input_frame: 'world'
