---
xpassthrough:
  filter_field_name: x
  filter_limit_min: -0.3
  filter_limit_max: 0.1
  filter_limit_negative: False
  input_frame: 'world' 

ypassthrough:
  filter_field_name: y
  filter_limit_min: 0.0
  filter_limit_max: 0.3
  filter_limit_negative: False
  input_frame: 'world'

zpassthrough:
  filter_field_name: z
  filter_limit_min: 0.10
  filter_limit_max: 0.5
  filter_limit_negative: False
  input_frame: 'world'
  
input_pc_topic: "/camera/depth_registered/points"
output_pc_topic: "/filtered_pc"
observed_frame_id: "/camera_rgb_optical_frame"
filtered_frame_id: "/world"
